<a href="https://colab.research.google.com/github/ManasviAtGitHub/pytorch_deep_learning/blob/main/PyTorch_01_Dealing_with_Tensors_and_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating Tensors

PyTorch tensors are created using torch.tensor()

In [49]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [50]:
scalar.ndim

0

In [51]:
# get tensor back as python int
scalar.item()

7

In [52]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [53]:
vector.ndim

1

In [54]:
vector.shape

torch.Size([2])

In [55]:
## matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [56]:
matrix.ndim

2

In [57]:
matrix[1]

tensor([ 9, 10])

In [58]:
matrix.shape

torch.Size([2, 2])

In [59]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [60]:
TENSOR.ndim

3

In [61]:
TENSOR.shape

torch.Size([1, 3, 3])

In [62]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

Why so?
You initialize neural networks through random numbers

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers(until the model is trained and this numbers represents weights in the model)


In [64]:
# Create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2939, 0.0040, 0.3728, 0.2729],
        [0.0731, 0.1096, 0.6442, 0.7178],
        [0.8442, 0.4454, 0.2563, 0.9332]])

In [65]:
random_tensor.ndim,  random_tensor.shape

(2, torch.Size([3, 4]))

In [66]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7625, 0.4413, 0.3073, 0.1305],
         [0.5046, 0.0679, 0.2895, 0.5791],
         [0.5860, 0.1314, 0.3388, 0.1929]]])

In [67]:
random_tensor.ndim,  random_tensor.shape

(3, torch.Size([1, 3, 4]))

### Zeroes and Ones

In [68]:
# create a tensor of all zeros
zeroes = torch.zeros(3,4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
zeroes.dtype ## default data type

torch.float32

In [70]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [71]:
# use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
# creating tensors like
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [73]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.2],
                               dtype = None, # what datatype is the tensor (eg. float32, float16...)
                               device = None, # what device your tensor is on (cpu or gpu)
                               requires_grad= False, # wheether or not to track gradients with this tensors operations
                               )

float_32_tensor

tensor([3.0000, 6.0000, 9.2000])

In [74]:
float_32_tensor.dtype

torch.float32

In [75]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3.0000, 6.0000, 9.2031], dtype=torch.float16)

In [76]:
#attributes of tensors
print(f"Datatype of tensor : {float_16_tensor.dtype}")
print(f"Shape of tensor : {float_16_tensor.shape}")
print(f"Device tensor is on : {float_16_tensor.device}")

Datatype of tensor : torch.float16
Shape of tensor : torch.Size([3])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [77]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [78]:
# multiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [79]:
# subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [80]:
## trying built-in functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [81]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [82]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

### Matrix Multiplication

* Element wise
* Dot product

Rules for multiplication (Dot product)

**Inner dimensions must match**
* (3,2) @ (3,2) => Err
* (3,2) @ (2,3) => Will work
* (2,3) @ (3,2) => Will work

**Outer dimensions results as output**
* (3,2) @ (2,3) => (3,3)
* (2,3) @ (3,2) => (2,2)


In [83]:
print(f"{tensor} * {tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [84]:
# element-wise
tensor * tensor

tensor([1, 4, 9])

In [85]:
# dot product
torch.matmul(tensor, tensor)

tensor(14)

In [86]:
tensor @ tensor

tensor(14)

In [87]:
tensorA = torch.tensor ([[1,2,3],[4,5,6]])
tensorB = torch.tensor ([[10,20,30],[40,50,60]])

In [88]:
tensorA.shape, tensorB.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [89]:
torch.mm(tensorA, tensorB) ## To resolve this, use transpose to match dimension)

RuntimeError: ignored

In [90]:
tensorB.T

tensor([[10, 40],
        [20, 50],
        [30, 60]])

In [91]:
torch.mm(tensorA, tensorB.T)

tensor([[140, 320],
        [320, 770]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [92]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [93]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [94]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [96]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [97]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [98]:
# find the position in tensor that has the minimum value with argmin -> returns index
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [99]:
# find the position in tensor that has the maximum value with argmin -> returns index
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping -  reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking -  combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -  removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute -  return a view of the input with dimensions permuted (swapped) in certain way.


In [100]:
import torch
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [101]:
## add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [102]:
## change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [103]:
## changing z changes x (because a view of a tensor shares the same memory as the orginal)
z[:,0] = 5

z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [107]:
## stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim =0)

x_stacked, x_stacked.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [109]:
## squeeze: removes all single dimensions from a target tensor
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

## remove extra dimensiokns from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

Previous tensor : tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Previous shape : torch.Size([9, 1])

New tensor : tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape : torch.Size([9])


In [110]:
# unsqueeze: adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

## add extra dimensiokns
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous tensor : tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape : torch.Size([9])

New tensor : tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape : torch.Size([1, 9])


In [111]:
# permute:  rearranges the dimensions of target tensor in specified order
x_original = torch.rand(size = (224,224,3))

# permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0 (3,224,224)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
### Indexing with PyTorch is similar to indexing with NumPy

In [114]:
# create a tensor
import torch
x =  torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [115]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [116]:
x[0][0]

tensor([1, 2, 3])

In [117]:
x[0][0][0]

tensor(1)

In [118]:
# use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [119]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [120]:
# get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [121]:
#get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensors and Numpy

As NumPy is popular scientific library, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()


In [123]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0) # default dtype is float64
tensor = torch.from_numpy(array) # matches the default type (otherwise its float32)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [124]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [125]:
# Tensor to NumPy array
tensor =  torch.ones(7)
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to represent the data better \-> again->again...`

Essentially what the random seed does in "flavour" the randomness

In [127]:
import torch
# create two random tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_C


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

## Running tensors and PyTorch objects on the GPU's (and making faster computations)

GPUs= faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes

In [2]:
!nvidia-smi

Sat Jul 15 11:48:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
## Check for gpu access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
## setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# count number of devices
torch.cuda.device_count()

1

In [6]:
## putting tensors and models on the GPU (results in faster computation)

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
#moving tensor back to the cpu (need to do for performing manipulations like using numpy)

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_on_cpu

array([1, 2, 3])